# Generated by Django 4.0.6 on 2022-08-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_platoon_app', '0022_user_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_pic',
            field=models.ImageField(default='users/default.jpg', upload_to='pets/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='users/default.jpg', upload_to='users/', verbose_name='Image'),
        ),
    ]
