# Generated by Django 4.0.6 on 2022-08-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_platoon_app', '0023_alter_pet_pet_pic_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_pic',
            field=models.ImageField(default='pets/default-pet-pic.jpg', upload_to='pets/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='users/default-profile-icon.jpg', upload_to='users/', verbose_name='Image'),
        ),
    ]
