# Generated by Django 4.0.6 on 2022-08-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_platoon_app', '0024_alter_pet_pet_pic_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='walk_track',
            field=models.JSONField(default={'track': 'empty'}),
        ),
    ]
