# Generated by Django 4.0.6 on 2022-08-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paw_platoon_app', '0028_user_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2),
        ),
    ]
